name: step_generate_configs
inputs:
  targetFolder:
    required: false
    default: "."
    type: string
runs:
  using: composite
  steps:
  - name: Generate the connections config file
    working-directory: ${{ github.workspace }}
    shell: pwsh
    run: |
      pip list
      echo "Generating connection config file..."
      python ./scripts/building/generate_connection_config.py `
          --target_folder ${{ inputs.targetFolder }}
